title:  S M Cusick's Data Science Portfolio
email: sean.matthew.cusick@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Seàn M. Cusick's Data Science Portfolio showcases projects in data analysis, data visualisation, and predictive modeling.
  Demonstrating expertise in Python, R, and SQL, Seán delivers actionable insights from complex data.
  <hr>
  Currently seeking Data Analyst or Business Analyst opportunities.
baseurl: "" 
url: "https://sean-m-cusick.github.io/" 
twitter_username: s_m_cusick
github_username:  sean-m-cusick

# Build settings
markdown: kramdown

plugins:
- jekyll-tabs 
- jekyll-seo-tag
- jekyll-feed
- jekyll-sass-converter
- _plugins
- jekyll-github-metadata

# Permalinks
permalink: pretty

# Collections
collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

sass:
  style: compressed
  
  # or expanded, nested, compact

# Exclude from processing.
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
